### ISSUE TITLE
README.md latest version is 2.3.9

### ISSUE THREAD

**Issue by salme146** [zdefne-usgs/ocean-iso-metadata#19]
To handle some issues Zafer brought up with the ncISO utility ; the latest version is 2.3.9

Thanks for letting me know. All of the XSL and the Java code originates from work done by @dneufeldcu and colleagues. I am just the caretaker. I made 2.3.9 official.

https://github.com/NOAA-PMEL/uafnciso/issues/21

**Comment by zdefne-usgs** [comment]
Cool. Looks like updating to 2.3.9 solved your problem as well. Feel free to reopen this issue if that's not the case...
