### ISSUE TITLE
custom style sheet

### ISSUE THREAD

**Issue by salme146** [zdefne-usgs/ocean-iso-metadata#20]
Is the .xsl stylesheet the most updated version? I got another copy from John Warner today and wanted to make sure they were the same on this page. Just wanted to help update this utility.

**Comment by zdefne-usgs** [comment]
The latest .xsl style sheet should be the most recently updated file under the [XSL /usgs_current](https://github.com/zdefne-usgs/ocean-iso-metadata/tree/master/XSL/usgs_current).
